### ISSUE TITLE
Feature request: Filter for changed nodes (since version X)

### ISSUE THREAD

**Issue by jbemmel** [nokia/srlinux-yang-models#1]
e.g. at https://yang.srlinux.dev/v22.11.2/tree.html

In 22.11.1 a change was introduced for routing-policy/policy/(default-)action/policy-result, I presume to be more in line with OpenConfig models

Such breaking changes should be flagged/annotated using revision tags, and the tool should (have an option to) highlight them

**Comment by jbemmel** [comment]
Alternatively, in light of the new platform/feature filtering at https://yang.srlinux.dev/release/v22.11.2/, a similar filter could be added for changes since version X

**Comment by hellt** [comment]
this is now done in the UI
